// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddReleaseDate_DateAdded_Stock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReleaseDate_DateAdded_Stock));
        
        string IMigrationMetadata.Id
        {
            get { return "202412090441546_AddReleaseDate_DateAdded_Stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
